GTM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('earnings/', include('earnings.urls')),
    path('workout/', include('workout.urls')),
    path('whiskey/', include('whiskey.urls')),
]

earnings/urls.py
from django.urls import path
from . import views
from earnings.views import TripListView, TripCreateView, FlightListView, EventListView, HotelListView, FlightCreateView, HotelCreateView, EventCreateView, TripDetailView, gapminder, EventUpdateView, EventDeleteView, chart

app_name = "earnings"

urlpatterns = [
    path('', TripListView.as_view(), name='index'),
    path('trips/<int:pk>/', TripDetailView.as_view(), name='trip_detail'),
    path('trips/create/', TripCreateView.as_view(), name='trip_create'),
    path('flights/', FlightListView.as_view(), name='flights'),
    path('flights/create/', FlightCreateView.as_view(), name='flight_create'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotels/create/', HotelCreateView.as_view(), name='hotel_create'),
    path('events/', EventListView.as_view(), name='events'),
    path('events/create/', EventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('gapminder/', gapminder, name='gapminder'),
    path('chart/', chart, name='chart'),
    path('get-weather/', views.get_weather, name='get_weather'),
]

earnings/models.py
from django.db import models

class Trip(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    flights = models.ManyToManyField("Flight", blank=True)
    hotels = models.ManyToManyField("Hotel", blank=True)
    events = models.ManyToManyField("Event")
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
    def get_total_cost(self):
        total = 0
        for flight in self.flights.all():
            total += flight.cost
        for hotel in self.hotels.all():
            total += hotel.cost
        for event in self.events.all():
            total += event.cost
        return total
    
class Flight(models.Model):
    name = models.CharField(max_length=200)
    origin = models.CharField(max_length=60)
    destination = models.CharField(max_length=60)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    airline = models.CharField(max_length=60)
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
class Hotel(models.Model):
    name = models.CharField(max_length=200)
    hotel_chain = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    website = models.URLField()
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name

earnings/views.py
from .models import Trip, Flight, Hotel, Event
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy
import subprocess
import sys
import os
from django.utils import timezone
import requests
from django.conf import settings
from django.http import JsonResponse

def execute_chart_update():
    chart_update_path = r"C:\Users\alexp\Documents\GTM\notebooks\chart_update.py"

    # Activate the virtual environment
    venv_path = r"C:\Users\alexp\Documents\GTM\.venv\Scripts\activate"
    activate_cmd = f"source {venv_path}" if sys.platform.startswith("linux") else f"activate {venv_path}"
    subprocess.run(activate_cmd, shell=True, check=True)

    # Execute the chart_update.py script using the python command
    subprocess.run([sys.executable, chart_update_path])

class TripListView(ListView):
    model = Trip
    template_name = 'earnings/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_trips'] = self.get_queryset().filter(start_date__gte=today)
        context['past_trips'] = self.get_queryset().filter(start_date__lt=today)
        return context

class TripDetailView(DetailView):
    model = Trip
    template_name = 'earnings/trip_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['flights'] = Flight.objects.filter(trip=self.object)
        context['hotels'] = Hotel.objects.filter(trip=self.object)
        context['events'] = Event.objects.filter(trip=self.object)
        return context
    
class TripCreateView(CreateView):
    model = Trip
    fields = ['name', 'start_date', 'end_date', 'flights', 'hotels', 'events', 'shared']
    success_url = reverse_lazy('earnings:index')
    template_name = 'earnings/trip_form.html'

class FlightListView(ListView):
    model = Flight
    template_name = 'earnings/flights.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_flights'] = self.get_queryset().filter(start_date__gte=today)
        context['past_flights'] = self.get_queryset().filter(start_date__lt=today)
        return context

class FlightCreateView(CreateView):
    model = Flight
    fields = ['name', 'origin', 'destination', 'start_date', 'end_date', 'cost', 'airline', 'shared']
    template_name = 'earnings/flight_form.html'
    success_url = reverse_lazy('earnings:flights')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class HotelListView(ListView):
    model = Hotel
    template_name = 'earnings/hotels.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_hotels'] = self.get_queryset().filter(start_date__gte=today)
        context['past_hotels'] = self.get_queryset().filter(start_date__lt=today)
        return context

class HotelCreateView(CreateView):
    model = Hotel
    fields = ['name', 'hotel_chain', 'city', 'state', 'start_date', 'end_date', 'cost', 'shared']
    template_name = 'earnings/hotel_form.html'
    success_url = reverse_lazy('earnings:hotels')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventListView(ListView):
    model = Event
    template_name = 'earnings/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_events'] = self.get_queryset().filter(start_date__gte=today)
        context['past_events'] = self.get_queryset().filter(start_date__lt=today)
        return context

class EventCreateView(CreateView):
    model = Event
    fields = ['name', 'description', 'city', 'state', 'start_date', 'end_date', 'cost', 'website', 'shared']
    template_name = 'earnings/event_form.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventUpdateView(UpdateView):
    model = Event
    fields = ['name', 'description', 'city', 'state', 'start_date', 'end_date', 'cost', 'website', 'shared']
    template_name = 'earnings/event_form.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventDeleteView(DeleteView):
    model = Event
    template_name = 'earnings/event_delete.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

# display gapminder html
def gapminder(request):
    return render(request, 'earnings/gapminder_2007.html')

def chart(request):
    return render(request, 'earnings/chart.html')

def get_weather(request):
    api_key = settings.WEATHER_API_KEY
    api_url = settings.WEATHER_API_URL
    city_name = request.GET.get('city', 'London')  # Default city is London

    params = {'q': city_name, 'appid': api_key, 'units': 'metric'}
    response = requests.get(api_url, params=params)

    if response.status_code == 200:
        data = response.json()
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Unable to fetch weather data.'}, status=500)

earnings/templates/earnings/event_delete.html
{% extends 'base/base.html' %}

{% block content %}

<section class="section">
    <div class="container">
        <h2 class="title">Confirm Deletion</h2>
        <div class="notification is-danger">
            <p><strong>Are you sure you want to delete this event?</strong></p>
            <p>{{ object.name }}</p>
        </div>
        <form method="post">
            {% csrf_token %}
            <button class="button is-danger" type="submit">Delete</button>
            <a href="{% url 'earnings:events' %}" class="button">Cancel</a>
        </form>
    </div>
</section>

{% endblock content %}

earnings/templates/earnings/event_form.html
{% extends 'base/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <h2 class="title">Add Event</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Event Name</label>
                        <div class="control">
                            <input class="input" type="text" name="name" value="{{ form.name.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Description</label>
                        <div class="control">
                            <input class="input" type="text" name="description" value="{{ form.description.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">City</label>
                        <div class="control">
                            <input class="input" type="text" name="city" value="{{ form.city.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">State</label>
                        <div class="control">
                            <input class="input" type="text" name="state" value="{{ form.state.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Start Date</label>
                        <div class="control">
                            <input class="input" type="date" name="start_date" value="{{ form.start_date.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">End Date</label>
                        <div class="control">
                            <input class="input" type="date" name="end_date" value="{{ form.end_date.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Cost</label>
                        <div class="control">
                            <input class="input" type="text" name="cost" value="{{ form.cost.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Website</label>
                        <div class="control">
                            <input class="input" type="text" name="website" value="{{ form.website.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Shared</label>
                        <div class="control">
                            <input class="input" type="text" name="shared" value="{{ form.shared.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/events.html
{% extends 'base/base.html' %}

{% block content %}

<section class="section">
    <a href="{% url 'earnings:event_create' %}" class="button is-primary">Create New Event</a>
    <br>
    <br>
    <h3 class="sub_title">Upcoming Events</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Event</th>
                    <th style="background-color: #5892b1;">City</th>
                    <th style="background-color: #5892b1;">State</th>
                    <th style="background-color: #5892b1;">Start Date</th>
                    <th style="background-color: #5892b1;">End Date</th>
                    <th style="background-color: #5892b1;">Description</th>
                    <th style="background-color: #5892b1;">Cost</th>
                    <th style="background-color: #5892b1;">Website</th>
                    <th style="background-color: #5892b1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for event in upcoming_events %}
                <tr>
                    <td>{{ event.name }}</td>
                    <td>{{ event.city }}</td>
                    <td>{{ event.state }}</td>
                    <td>{{ event.start_date }}</td>
                    <td>{{ event.end_date }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.cost }}</td>
                    <td>{{ event.website }}</td>
                    <td>
                        <a href="{% url 'earnings:event_update' event.pk %}" class="button is-primary is-small">Edit</a>
                        <a href="{% url 'earnings:event_delete' event.pk %}" class="button is-danger is-small">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <h3 class="sub_title">Past Events</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Event</th>
                    <th style="background-color: #5892b1;">City</th>
                    <th style="background-color: #5892b1;">State</th>
                    <th style="background-color: #5892b1;">Start Date</th>
                    <th style="background-color: #5892b1;">End Date</th>
                    <th style="background-color: #5892b1;">Description</th>
                    <th style="background-color: #5892b1;">Cost</th>
                    <th style="background-color: #5892b1;">Website</th>
                    <th style="background-color: #5892b1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for event in past_events %}
                <tr>
                    <td>{{ event.name }}</td>
                    <td>{{ event.city }}</td>
                    <td>{{ event.state }}</td>
                    <td>{{ event.start_date }}</td>
                    <td>{{ event.end_date }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.cost }}</td>
                    <td>{{ event.website }}</td>
                    <td>
                        <a href="{% url 'earnings:event_update' event.pk %}" class="button is-primary is-small">Edit</a>
                        <a href="{% url 'earnings:event_delete' event.pk %}" class="button is-danger is-small">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/flight_form.html
{% extends 'base/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <h2 class="title">Add a New Flight</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Flight Name</label>
                        <div class="control">
                            <input class="input" type="text" name="name" value="{{ form.name.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Origin</label>
                        <div class="control">
                            <input class="input" type="text" name="origin" value="{{ form.origin.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Destination</label>
                        <div class="control">
                            <input class="input" type="text" name="destination" value="{{ form.destination.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Start Date</label>
                        <div class="control">
                            <input class="input" type="date" name="start_date" value="{{ form.start_date.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">End Date</label>
                        <div class="control">
                            <input class="input" type="date" name="end_date" value="{{ form.end_date.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Cost</label>
                        <div class="control">
                            <input class="input" type="text" name="cost" value="{{ form.cost.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Airline</label>
                        <div class="control">
                            <input class="input" type="text" name="airline" value="{{ form.airline.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Shared</label>
                        <div class="control">
                            <input class="input" type="text" name="shared" value="{{ form.shared.value }}">
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/flights.html
{% extends 'base/base.html' %}

{% block content %}

<section class="section">
    <a href="{% url 'earnings:flight_create' %}" class="button is-primary">Create New Flight</a>
    <br>
    <br>
    <h3 class="sub_title">Upcoming Flights</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Flight</th>
                    <th style="background-color: #5892b1;">Origin</th>
                    <th style="background-color: #5892b1;">Destination</th>
                    <th style="background-color: #5892b1;">Departure Date</th>
                    <th style="background-color: #5892b1;">Return Date</th>
                    <th style="background-color: #5892b1;">Price</th>
                    <th style="background-color: #5892b1;">Airline</th>
                </tr>
            </thead>
            <tbody>
                {% for flight in upcoming_flights %}
                <tr>
                    <td>{{ flight.name }}</td>
                    <td>{{ flight.origin }}</td>
                    <td>{{ flight.destination }}</td>
                    <td>{{ flight.start_date }}</td>
                    <td>{{ flight.end_date }}</td>
                    <td>{{ flight.cost }}</td>
                    <td>{{ flight.airline }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <h3 class="sub_title">Past Flights</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Flight</th>
                    <th style="background-color: #5892b1;">Origin</th>
                    <th style="background-color: #5892b1;">Destination</th>
                    <th style="background-color: #5892b1;">Departure Date</th>
                    <th style="background-color: #5892b1;">Return Date</th>
                    <th style="background-color: #5892b1;">Price</th>
                    <th style="background-color: #5892b1;">Airline</th>
                </tr>
            </thead>
            <tbody>
                {% for flight in past_flights %}
                <tr>
                    <td>{{ flight.name }}</td>
                    <td>{{ flight.origin }}</td>
                    <td>{{ flight.destination }}</td>
                    <td>{{ flight.start_date }}</td>
                    <td>{{ flight.end_date }}</td>
                    <td>{{ flight.cost }}</td>
                    <td>{{ flight.airline }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/hotels.html
{% extends 'base/base.html' %}

{% block content %}

<section class="section">
    <a href="{% url 'earnings:hotel_create' %}" class="button is-primary">Create New Hotel Stay</a>
    <br>
    <br>
    <h3 class="sub_title">Upcoming Hotel Stays</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Hotel</th>
                    <th style="background-color: #5892b1;">Hotel Chain</th>
                    <th style="background-color: #5892b1;">City</th>
                    <th style="background-color: #5892b1;">State</th>
                    <th style="background-color: #5892b1;">Check-In</th>
                    <th style="background-color: #5892b1;">Check-Out</th>
                    <th style="background-color: #5892b1;">Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for hotel in upcoming_hotels %}
                <tr>
                    <td>{{ hotel.name }}</td>
                    <td>{{ hotel.hotel_chain }}</td>
                    <td>{{ hotel.city }}</td>
                    <td>{{ hotel.state }}</td>
                    <td>{{ hotel.start_date }}</td>
                    <td>{{ hotel.end_date }}</td>
                    <td>{{ hotel.cost }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <h3 class="sub_title">Past Hotel Stays</h3>
    <div class="table-container">
        <table class="table is-bordered is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th style="background-color: #5892b1;">Hotel</th>
                    <th style="background-color: #5892b1;">Hotel Chain</th>
                    <th style="background-color: #5892b1;">City</th>
                    <th style="background-color: #5892b1;">State</th>
                    <th style="background-color: #5892b1;">Check-In</th>
                    <th style="background-color: #5892b1;">Check-Out</th>
                    <th style="background-color: #5892b1;">Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for hotel in past_hotels %}
                <tr>
                    <td>{{ hotel.name }}</td>
                    <td>{{ hotel.hotel_chain }}</td>
                    <td>{{ hotel.city }}</td>
                    <td>{{ hotel.state }}</td>
                    <td>{{ hotel.start_date }}</td>
                    <td>{{ hotel.end_date }}</td>
                    <td>{{ hotel.cost }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/index.html
{% extends 'base/base.html' %}

{% block content %}

<section class="section">
    <a href="{% url 'earnings:trip_create' %}" class="button is-primary">Create New Trip</a>
    <br>
    <br>
    <div class="columns">
        <div class="column is-half">
            <h5 class="sub_title">Upcoming Trips</h5>
            <div class="table-container">
                <table class="table is-bordered is-hoverable is-fullwidth">
                    <thead class="header-cell">
                        <tr>
                            <th style="background-color: #5892b1;">Trip Name</th>
                            <th style="background-color: #5892b1;">Start Date</th>
                            <th style="background-color: #5892b1;">End Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for trip in upcoming_trips %}
                        <tr>
                            <td><a href="{% url 'earnings:trip_detail' trip.id %}">{{ trip.name }}</a></td>
                            <td>{{ trip.start_date }}</td>
                            <td>{{ trip.end_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="column">
            <h5 class="sub_title">Past Trips</h3>
            <div class="table-container">
                <table class="table is-bordered is-hoverable is-fullwidth">
                    <thead class="header-cell">
                        <tr>
                            <th style="background-color: #5892b1;">Trip Name</th>
                            <th style="background-color: #5892b1;">Start Date</th>
                            <th style="background-color: #5892b1;">End Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for trip in past_trips %}
                        <tr>
                            <td><a href="{% url 'earnings:trip_detail' trip.id %}">{{ trip.name }}</a></td>
                            <td>{{ trip.start_date }}</td>
                            <td>{{ trip.end_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

earnings/templates/earnings/weather.html
{% extends 'base/base.html' %}

{% block content %}

<section>
    <h1>Weather Information</h1>
    <input type="text" id="cityInput" placeholder="Enter city name">
    <button onclick="getWeather()">Get Weather</button>

    <div id="weatherInfo">
        <!-- Weather data will be displayed here -->
    </div>

    <script>
        function getWeather() {
            var cityName = document.getElementById('cityInput').value;
            var url = `/weather/get-weather/?city=${cityName}`;

            fetch(url)
                .then(response => response.json())
                .then(data => {
                    // Handle the weather data and update the weatherInfo div
                    var weatherInfoDiv = document.getElementById('weatherInfo');
                    weatherInfoDiv.innerHTML = `Temperature: ${data.main.temp}°C<br>
                                                Description: ${data.weather[0].description}`;
                })
                .catch(error => {
                    console.error('Error fetching weather data:', error);
                });
        }
    </script>
</section>

{% endblock content %}