GTM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('earnings/', include('earnings.urls')),
    path('workout/', include('workout.urls')),
    path('whiskey/', include('whiskey.urls')),
]

earnings/urls.py
from django.urls import path
from . import views
from earnings.views import TripListView, TripCreateView, FlightListView, EventListView, HotelListView, FlightCreateView, HotelCreateView, EventCreateView, TripDetailView, gapminder, EventUpdateView, EventDeleteView, chart

app_name = "earnings"

urlpatterns = [
    path('', TripListView.as_view(), name='index'),
    path('trips/<int:pk>/', TripDetailView.as_view(), name='trip_detail'),
    path('trips/create/', TripCreateView.as_view(), name='trip_create'),
    path('flights/', FlightListView.as_view(), name='flights'),
    path('flights/create/', FlightCreateView.as_view(), name='flight_create'),
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('hotels/create/', HotelCreateView.as_view(), name='hotel_create'),
    path('events/', EventListView.as_view(), name='events'),
    path('events/create/', EventCreateView.as_view(), name='event_create'),
    path('events/<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('gapminder/', gapminder, name='gapminder'),
    path('chart/', chart, name='chart'),
    path('get-weather/', views.get_weather, name='get_weather'),
]

earnings/models.py
from django.db import models

class Trip(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    flights = models.ManyToManyField("Flight", blank=True)
    hotels = models.ManyToManyField("Hotel", blank=True)
    events = models.ManyToManyField("Event")
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
    def get_total_cost(self):
        total = 0
        for flight in self.flights.all():
            total += flight.cost
        for hotel in self.hotels.all():
            total += hotel.cost
        for event in self.events.all():
            total += event.cost
        return total
    
class Flight(models.Model):
    name = models.CharField(max_length=200)
    origin = models.CharField(max_length=60)
    destination = models.CharField(max_length=60)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    airline = models.CharField(max_length=60)
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
class Hotel(models.Model):
    name = models.CharField(max_length=200)
    hotel_chain = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name
    
class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    start_date = models.DateField()
    end_date = models.DateField()
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    website = models.URLField()
    shared = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_date"]

    def __str__(self):
        return self.name

earnings/views.py
from .models import Trip, Flight, Hotel, Event
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy
import subprocess
import sys
import os
from django.utils import timezone
import requests
from django.conf import settings
from django.http import JsonResponse

def execute_chart_update():
    chart_update_path = r"C:\Users\alexp\Documents\GTM\notebooks\chart_update.py"

    # Activate the virtual environment
    venv_path = r"C:\Users\alexp\Documents\GTM\.venv\Scripts\activate"
    activate_cmd = f"source {venv_path}" if sys.platform.startswith("linux") else f"activate {venv_path}"
    subprocess.run(activate_cmd, shell=True, check=True)

    # Execute the chart_update.py script using the python command
    subprocess.run([sys.executable, chart_update_path])

class TripListView(ListView):
    model = Trip
    template_name = 'earnings/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_trips'] = self.get_queryset().filter(start_date__gte=today)
        context['past_trips'] = self.get_queryset().filter(start_date__lt=today)
        return context

class TripDetailView(DetailView):
    model = Trip
    template_name = 'earnings/trip_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['flights'] = Flight.objects.filter(trip=self.object)
        context['hotels'] = Hotel.objects.filter(trip=self.object)
        context['events'] = Event.objects.filter(trip=self.object)
        return context
    
class TripCreateView(CreateView):
    model = Trip
    fields = ['name', 'start_date', 'end_date', 'flights', 'hotels', 'events', 'shared']
    success_url = reverse_lazy('earnings:index')
    template_name = 'earnings/trip_form.html'

class FlightListView(ListView):
    model = Flight
    template_name = 'earnings/flights.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_flights'] = self.get_queryset().filter(start_date__gte=today)
        context['past_flights'] = self.get_queryset().filter(start_date__lt=today)
        return context

class FlightCreateView(CreateView):
    model = Flight
    fields = ['name', 'origin', 'destination', 'start_date', 'end_date', 'cost', 'airline', 'shared']
    template_name = 'earnings/flight_form.html'
    success_url = reverse_lazy('earnings:flights')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class HotelListView(ListView):
    model = Hotel
    template_name = 'earnings/hotels.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_hotels'] = self.get_queryset().filter(start_date__gte=today)
        context['past_hotels'] = self.get_queryset().filter(start_date__lt=today)
        return context

class HotelCreateView(CreateView):
    model = Hotel
    fields = ['name', 'hotel_chain', 'city', 'state', 'start_date', 'end_date', 'cost', 'shared']
    template_name = 'earnings/hotel_form.html'
    success_url = reverse_lazy('earnings:hotels')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventListView(ListView):
    model = Event
    template_name = 'earnings/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = timezone.now().date()
        context['upcoming_events'] = self.get_queryset().filter(start_date__gte=today)
        context['past_events'] = self.get_queryset().filter(start_date__lt=today)
        return context

class EventCreateView(CreateView):
    model = Event
    fields = ['name', 'description', 'city', 'state', 'start_date', 'end_date', 'cost', 'website', 'shared']
    template_name = 'earnings/event_form.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventUpdateView(UpdateView):
    model = Event
    fields = ['name', 'description', 'city', 'state', 'start_date', 'end_date', 'cost', 'website', 'shared']
    template_name = 'earnings/event_form.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

class EventDeleteView(DeleteView):
    model = Event
    template_name = 'earnings/event_delete.html'
    success_url = reverse_lazy('earnings:events')

    def form_valid(self, form):
        response = super().form_valid(form)
        execute_chart_update()
        return response

# display gapminder html
def gapminder(request):
    return render(request, 'earnings/gapminder_2007.html')

def chart(request):
    return render(request, 'earnings/chart.html')

def get_weather(request):
    api_key = settings.WEATHER_API_KEY
    api_url = settings.WEATHER_API_URL
    city_name = request.GET.get('city', 'London')  # Default city is London

    params = {'q': city_name, 'appid': api_key, 'units': 'metric'}
    response = requests.get(api_url, params=params)

    if response.status_code == 200:
        data = response.json()
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Unable to fetch weather data.'}, status=500)

earnings/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
        <title>Travel.</title>
        {% block header %}{% endblock %}
    </head>

    <body>
        <!-- Add a background color below -->
        <section class="hero is-small is-bold" style="background-color: rgb(158, 157, 157);">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <h3 class="title">TripEx</h3>
                </div>
            </div>
        </section>
        <nav class="navbar is-dark is-expanded is-centered" role="navigation" aria-label="main navigation">
            <div id="navbarMain" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{% url 'earnings:index' %}">
                        Home
                    </a>
                    <a class="navbar-item" href="{% url 'earnings:flights' %}">
                        Flights
                    </a>
                    <a class="navbar-item" href="{% url 'earnings:hotels' %}">
                        Hotels
                    </a>
                    <a class="navbar-item" href="{% url 'earnings:events' %}">
                        Events
                    </a>
                    <a class="navbar-item" href="{% url 'earnings:chart' %}">
                        Chart
                    </a>
                </div>
            </div>
            <!-- <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light">
                            Log in
                        </a>
                    </div>
                </div>
            </div> -->
        </nav>
        {% block content %}{% endblock %}
    </body>
    <!-- <footer>
        <div class="container">
            <div class="columns">
                <div class="column">
                    <h1 class="title">Travel</h1>
                </div>
                <div class="column">
                    <h1 class="title">Contact</h1>
                </div>
                <div class="column">
                    <h1 class="title">Social Media</h1>
                </div>
            </div>
        </div>
    </footer> -->
</html>